---
name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version:
          - "3.11"

    steps:
      - uses: actions/checkout@v3

      - name: Install flit
        run: |
          pipx install flit

      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run linters
        run: |
          python3 -m venv .venv
          .venv/bin/pip install '.[lint]'
          make lint

      - name: Run golden tests
        run: |
          ./tests/golden/golden.sh

      - name: Build package
        run: |
          flit build

  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"

    steps:
      - uses: actions/checkout@v3

      - name: Install flit
        run: |
          pipx install flit

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: |
          python3 -m venv .venv
          .venv/bin/pip install '.[test]'
          make test
