---
name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: eifinger/setup-rye@v4.2.0
        id: setup-rye
        with:
          version: "0.36.0"
          enable-cache: true
          cache-prefix: "rye-lint"
      - name: Run linters
        run: rye lint

  golden:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Run golden tests
        run: |
          ./tests/golden/golden.sh

  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"

    steps:
      - uses: actions/checkout@v4
      - uses: eifinger/setup-rye@v4.2.0
        id: setup-rye
        with:
          version: "0.36.0"
      - name: Install Python ${{ matrix.python-version }}
        run: rye pin ${{ matrix.python-version }}
      - name: Run tests
        run: rye test
